const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#2DAAAE",
    background: "#F5F6FA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#2DAAAE",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2B4A",
    secondaryForeground: "#FFFFFF",
    muted: "#EAEDF2",
    mutedForeground: "#8E9BB0",
    accent: "#00C9B1",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#EAEDF2",
    input: "#EAEDF2",
    success: "#22C55E",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#3B82F6",
  },
  dark: {
    text: "#F5F6FA",
    tint: "#2DAAAE",
    background: "#0F172A",
    foreground: "#F5F6FA",
    card: "#1E293B",
    cardForeground: "#F5F6FA",
    primary: "#2DAAAE",
    primaryForeground: "#FFFFFF",
    secondary: "#334155",
    secondaryForeground: "#F5F6FA",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#00C9B1",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#334155",
    input: "#334155",
    success: "#22C55E",
    warning: "#F59E0B",
    error: "#EF4444",
    info: "#3B82F6",
  },
  radius: 12,
};

export default colors;
