// Generated by plugins/withIosSceneLifecycle.js — do not edit by hand.
//
// iOS 27 requires the scene life cycle. `ExpoAppSceneDelegate` creates the window
// from the connecting scene, starts React Native into it, and forwards scene, URL
// and user-activity events to the app delegate.
internal import Expo
import UIKit

class SceneDelegate: ExpoAppSceneDelegate {}
