/**
 * Expo config plugin — adopts the UIScene life cycle on iOS.
 *
 * iOS 27 terminates at launch (EXC_BREAKPOINT in
 * `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`) any app that
 * still drives its window from the app delegate alone. Expo ships the
 * `ExpoAppSceneDelegate` base class for this, but the SDK 57 prebuild template
 * does not wire it up yet, so this plugin does it on every prebuild:
 *
 *  1. adds `UIApplicationSceneManifest` to Info.plist, pointing at SceneDelegate
 *  2. writes `SceneDelegate.swift` (a subclass of `ExpoAppSceneDelegate`) and
 *     adds it to the Xcode target
 *  3. makes AppDelegate conform to `ExpoReactNativeFactoryProvider` and stop
 *     creating the window / starting React Native itself — under the scene life
 *     cycle the scene delegate owns the window and starts React Native into it.
 *
 * Remove this plugin once the Expo template adopts scenes on its own.
 */
const { withInfoPlist, withDangerousMod, withXcodeProject, withAppDelegate, IOSConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SCENE_DELEGATE_FILENAME = 'SceneDelegate.swift';

const SCENE_DELEGATE_SOURCE = `// Generated by plugins/withIosSceneLifecycle.js — do not edit by hand.
//
// iOS 27 requires the scene life cycle. \`ExpoAppSceneDelegate\` creates the window
// from the connecting scene, starts React Native into it, and forwards scene, URL
// and user-activity events to the app delegate.
internal import Expo
import UIKit

class SceneDelegate: ExpoAppSceneDelegate {}
`;

function withSceneManifest(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return cfg;
  });
}

function withSceneDelegateFile(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, cfg.modRequest.projectName);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, SCENE_DELEGATE_FILENAME), SCENE_DELEGATE_SOURCE);
      return cfg;
    },
  ]);
}

function withSceneDelegateInXcodeProject(config) {
  return withXcodeProject(config, (cfg) => {
    const projectName = cfg.modRequest.projectName;
    const filepath = `${projectName}/${SCENE_DELEGATE_FILENAME}`;

    if (!cfg.modResults.hasFile(filepath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project: cfg.modResults,
      });
    }
    return cfg;
  });
}

function withAppDelegateForScenes(config) {
  return withAppDelegate(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // Conform to the protocol the scene delegate reads the factory and window from.
    if (!contents.includes('ExpoReactNativeFactoryProvider')) {
      contents = contents.replace(
        /class AppDelegate: ExpoAppDelegate\b/,
        'class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider'
      );
    }

    // The scene delegate creates the window from the UIWindowScene; a window made
    // here belongs to no scene and would leave the app showing nothing.
    contents = contents.replace(
      /^[ \t]*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n/m,
      ''
    );

    // Likewise React Native is started by the scene delegate — starting it here too
    // would build a second root view that never appears on screen.
    contents = contents.replace(
      /^[ \t]*factory\.startReactNative\((?:.|\n)*?launchOptions: launchOptions\)\n/m,
      ''
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
}

module.exports = function withIosSceneLifecycle(config) {
  config = withSceneManifest(config);
  config = withSceneDelegateFile(config);
  config = withSceneDelegateInXcodeProject(config);
  config = withAppDelegateForScenes(config);
  return config;
};
