import { Patient, PatientAlert } from "../entities";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 1,
    name: "Ahmed Al-Rashid",
    dob: "1975-03-15",
    gender: "Male",
    phone: "+966 50 123 4567",
    email: "ahmed.rashid@email.com",
    address: "Riyadh, Al Olaya District",
    bloodType: "O+",
    status: "active",
    lastVisit: "2024-12-10",
    diagnosis: "Type 2 Diabetes",
  },
  {
    id: 2,
    name: "Fatima Al-Zahra",
    dob: "1988-07-22",
    gender: "Female",
    phone: "+966 55 987 6543",
    email: "fatima.zahra@email.com",
    address: "Jeddah, Al Hamra District",
    bloodType: "A+",
    status: "active",
    lastVisit: "2024-12-18",
    diagnosis: "Hypertension",
  },
  {
    id: 3,
    name: "Khalid Al-Mansouri",
    dob: "1962-11-05",
    gender: "Male",
    phone: "+966 56 456 7890",
    email: "khalid.mansouri@email.com",
    address: "Dammam, Al Faisaliyah",
    bloodType: "B-",
    status: "critical",
    lastVisit: "2024-12-20",
    diagnosis: "Chronic Heart Failure",
  },
  {
    id: 4,
    name: "Nora Al-Qahtani",
    dob: "1995-02-28",
    gender: "Female",
    phone: "+966 50 234 5678",
    email: "nora.qahtani@email.com",
    address: "Riyadh, Al Nuzha",
    bloodType: "AB+",
    status: "active",
    lastVisit: "2024-11-30",
    diagnosis: "Asthma",
  },
  {
    id: 5,
    name: "Omar Ibn Saud",
    dob: "1980-09-14",
    gender: "Male",
    phone: "+966 54 678 9012",
    email: "omar.ibnsaud@email.com",
    address: "Mecca, Al Aziziyah",
    bloodType: "O-",
    status: "inactive",
    lastVisit: "2024-09-05",
    diagnosis: "Lower Back Pain",
  },
  {
    id: 6,
    name: "Layla Al-Hassan",
    dob: "1970-12-01",
    gender: "Female",
    phone: "+966 58 345 6789",
    email: "layla.hassan@email.com",
    address: "Medina, Al Rawabi",
    bloodType: "A-",
    status: "active",
    lastVisit: "2024-12-15",
    diagnosis: "Rheumatoid Arthritis",
  },
  {
    id: 7,
    name: "Tariq Al-Otaibi",
    dob: "1955-06-20",
    gender: "Male",
    phone: "+966 51 567 8901",
    email: "tariq.otaibi@email.com",
    address: "Riyadh, Al Malaz",
    bloodType: "B+",
    status: "critical",
    lastVisit: "2024-12-22",
    diagnosis: "COPD",
  },
  {
    id: 8,
    name: "Hessa Al-Shammari",
    dob: "1992-04-10",
    gender: "Female",
    phone: "+966 59 789 0123",
    email: "hessa.shammari@email.com",
    address: "Jeddah, Al Rehab",
    bloodType: "O+",
    status: "active",
    lastVisit: "2024-12-19",
    diagnosis: "Migraine",
  },
];

export const MOCK_PATIENT_ALERTS: Record<number, PatientAlert> = {
  1: {
    allergies: [{ type: "Drug Allergies", value: "Vancomycin" }],
    contamination: ["dust"],
    instructions: "Monitor blood sugar levels every 4 hours. Adjust insulin as needed.",
    isolation: "Standard Precautions",
  },
  2: {
    allergies: [{ type: "Drug Allergies", value: "Penicillin" }],
    contamination: [],
    instructions: "Monitor blood pressure twice daily. Low sodium diet.",
    isolation: "",
  },
  3: {
    allergies: [
      { type: "Drug Allergies", value: "Aspirin" },
      { type: "Food Allergies", value: "Shellfish" },
    ],
    contamination: ["latex"],
    instructions: "Strict fluid restriction 1.5L/day. Daily weight monitoring.",
    isolation: "Contact Precautions",
  },
  4: {
    allergies: [],
    contamination: ["pollen"],
    instructions: "Ensure proper inhaler technique. Peak flow monitoring.",
    isolation: "",
  },
  6: {
    allergies: [{ type: "Drug Allergies", value: "Sulfonamides" }],
    contamination: [],
    instructions: "Joint protection measures. Gentle ROM exercises.",
    isolation: "",
  },
  8: {
    allergies: [],
    contamination: [],
    instructions: "Avoid known triggers. Keep headache diary.",
    isolation: "",
  },
};
