import { Platform, StyleSheet } from "react-native";

import { Colors } from "@/theme/colors";

export const visitDetailStyles = StyleSheet.create({
  container: { flex: 1 },
  topBar: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingBottom: 12, borderBottomWidth: 1, gap: 8 },
  iconBtn: { width: 38, height: 38, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  topTitle: { flex: 1, fontSize: 18, fontFamily: "Inter_600SemiBold" },
  topActions: { flexDirection: "row", gap: 8 },

  heroCard: { padding: 20 },
  heroTop: { flexDirection: "row", alignItems: "center", gap: 14 },
  heroName: { fontSize: 18, fontFamily: "Inter_700Bold", marginBottom: 4 },
  heroType: { fontSize: 14, fontFamily: "Inter_400Regular", marginBottom: 6, color: "#6B7280" },
  heroBadges: { flexDirection: "row", gap: 6, flexWrap: "wrap", marginTop: 4 },
  criticalBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#EF444418", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 12 },
  criticalDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#EF4444" },
  criticalText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: "#EF4444" },
  bloodBadge: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#F3F4F6", paddingHorizontal: 8, paddingVertical: 3, borderRadius: 12 },
  bloodText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  heroActions: { flexDirection: "row", gap: 10, paddingTop: 12, marginTop: 12, borderTopWidth: 1 },
  heroActionBtn: { flex: 1 },
  metaRow: { flexDirection: "row", gap: 16, paddingTop: 14, borderTopWidth: 1, flexWrap: "wrap" },
  metaItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  metaValue: { fontSize: 13, fontFamily: "Inter_500Medium" },

  checkoutOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", alignItems: "center", justifyContent: "center", padding: 28 },
  checkoutCard: {
    width: "100%", borderRadius: 24, paddingHorizontal: 28, paddingTop: 36, paddingBottom: 28,
    alignItems: "center", gap: 0, backgroundColor: "#FFFFFF",
    ...Platform.select({ web: { boxShadow: "0 20px 60px rgba(0,0,0,0.25)" }, default: {} }),
  },
  checkoutIconWrap: { width: 76, height: 76, borderRadius: 38, borderWidth: 3, borderColor: "#F59E0B", alignItems: "center", justifyContent: "center", marginBottom: 20 },
  checkoutIconText: { fontSize: 36, fontFamily: "Inter_700Bold", color: "#F59E0B", lineHeight: 44 },
  checkoutTitle: { fontSize: 17, fontFamily: "Inter_600SemiBold", textAlign: "center", lineHeight: 26, color: "#111827", marginBottom: 28, paddingHorizontal: 4 },
  checkoutBtns: { flexDirection: "row", gap: 10, width: "100%" },
  checkoutConfirmBtn: { flex: 1, paddingVertical: 16, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  checkoutCancelBtn: { flex: 1, paddingVertical: 16, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  checkoutBtnText: { color: "#fff", fontSize: 15, fontFamily: "Inter_700Bold", letterSpacing: 0.2 },

  section: { paddingHorizontal: 16, marginTop: 0,marginBottom: 14 },
  sectionHeader: { paddingHorizontal: 16, marginTop: 12 },
  sectionTitle: { fontSize: 15, fontFamily: "Inter_700Bold", marginBottom: 8 },
  sectionCard: { padding: 14 },

  rowWithAction: { flexDirection: "row", alignItems: "center", gap: 10 },
  rowIcon: { flexDirection: "row", alignItems: "center", gap: 12 },
  iconBox: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  rowValue: { fontSize: 15, fontFamily: "Inter_400Regular" },
  divider: { height: 1, marginVertical: 2 },
  teamRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 6 },
  teamName: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  teamRole: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  notesText: { fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 22 },

  visitInfoGrid: { flexDirection: "row", gap: 8 },
  visitInfoCell: { flex: 1, gap: 4 },
  visitInfoLabel: { fontSize: 11, fontFamily: "Inter_500Medium", letterSpacing: 0.2 },
  visitInfoValue: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  visitInfoDivider: { height: 1, marginVertical: 10 },

  dynRow: { borderWidth: 1, borderColor: "#E2E8F0", borderRadius: 10, padding: 10, gap: 8, marginBottom: 8, backgroundColor: "transparent" },
  addRowBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 10, borderRadius: 10, marginTop: 4 },
  removeRowBtn: { position: "absolute" as const, top: 6, right: 6, width: 22, height: 22, borderRadius: 11, backgroundColor: "#EF4444", alignItems: "center" as const, justifyContent: "center" as const },

  collapsibleHeader: { flexDirection: "row", alignItems: "center", gap: 8, padding: 14, borderBottomWidth: 1 },
  collapsibleTitle: { fontSize: 14, fontFamily: "Inter_700Bold" },
  badge: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6, minWidth: 22, alignItems: "center" },
  badgeText: { fontSize: 11, fontFamily: "Inter_700Bold" },

  alertCard: { borderLeftWidth: 4, borderRadius: 8, padding: 12 },
  alertCardTitle: { fontSize: 12, fontFamily: "Inter_700Bold", color: "#EF4444", letterSpacing: 0.5 },
  alertRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
  alertRowText: { fontSize: 13, fontFamily: "Inter_400Regular", color: "#7F1D1D", flex: 1 },
  alertInstrText: { fontSize: 13, fontFamily: "Inter_400Regular", color: "#78350F", lineHeight: 20 },

  flowSection: { gap: 8 },
  flowSectionTitle: { fontSize: 13, fontFamily: "Inter_700Bold", textAlign: "center", paddingVertical: 8, borderRadius: 8, overflow: "hidden", letterSpacing: 0.3 },
  flowSubTitle: { fontSize: 12, fontFamily: "Inter_700Bold", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, overflow: "hidden", alignSelf: "stretch", letterSpacing: 0.3 },
  formField: { marginTop: 2 },
  formLabel: { fontSize: 12, fontFamily: "Inter_500Medium", marginBottom: 4 },
  formSubhead: { fontSize: 13, fontFamily: "Inter_600SemiBold", marginTop: 4 },
  formInput: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14, fontFamily: "Inter_400Regular" },
  formRow: { flexDirection: "row", gap: 10 },
  scoreChip: { width: 34, height: 34, borderRadius: 8, borderWidth: 1.5, alignItems: "center", justifyContent: "center" },

  radioRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  radioOuter: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, alignItems: "center", justifyContent: "center" },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: Colors.primary },
  radioLabel: { fontSize: 13, fontFamily: "Inter_500Medium" },

  medCard: { borderWidth: 1, borderRadius: 10, padding: 12, marginBottom: 8 },
  medDrug: { fontSize: 13, fontFamily: "Inter_700Bold", marginBottom: 6 },
  medGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  medCell: { minWidth: "45%" as any, paddingVertical: 2 },
  medCellLabel: { fontSize: 10, fontFamily: "Inter_600SemiBold", color: "#9CA3AF", letterSpacing: 0.3 },
  medCellVal: { fontSize: 12, fontFamily: "Inter_500Medium", marginTop: 1 },
  medAdminBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 6 },
  medAdminBtn: { paddingHorizontal: 18, paddingVertical: 7, borderRadius: 8 },

  invRow: { flexDirection: "row", alignItems: "center", padding: 12, borderRadius: 10, borderWidth: 1 },
  invName: { fontSize: 14, fontFamily: "Inter_600SemiBold", marginBottom: 2 },
  useBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },

  procTimeInput: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, gap: 8, marginTop: 4 },
  procTimeText: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  procSaveBtn: { alignItems: "center", justifyContent: "center", paddingVertical: 12, borderRadius: 10, marginTop: 14 },
  readOnlyBanner: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: "#6B7280", paddingVertical: 10, paddingHorizontal: 14, borderRadius: 10 },
  readOnlyBannerText: { color: "#fff", fontSize: 13, fontFamily: "Inter_600SemiBold" },

  saveFlowBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 13, borderRadius: 12, gap: 8 },

  actionsRow: { paddingHorizontal: 16, paddingTop: 24, paddingBottom: 8 },
  mainBtn: { flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 15, borderRadius: 14, gap: 8 },
  mainBtnText: { fontSize: 15, fontFamily: "Inter_600SemiBold", color: "#fff" },

  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalContent: { borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: "85%", overflow: "hidden" },
  modalHeader: { flexDirection: "row", alignItems: "center", gap: 10, padding: 16 },
  modalHeaderTitle: { fontSize: 15, fontFamily: "Inter_700Bold", color: "#fff" },
  modalHeaderSub: { fontSize: 11, fontFamily: "Inter_400Regular", color: "rgba(255,255,255,0.8)" },
  modalItemRow: { flexDirection: "row", gap: 10 },
  modalItemBox: { flex: 1, borderWidth: 1, borderRadius: 10, padding: 12 },
  modalItemLabel: { fontSize: 10, fontFamily: "Inter_600SemiBold", letterSpacing: 0.5, marginBottom: 6 },
  modalItemName: { fontSize: 16, fontFamily: "Inter_700Bold" },
  modalItemCode: { fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 4 },
  qtyBadge: { width: 24, height: 24, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  qtyAvailText: { fontSize: 13, fontFamily: "Inter_500Medium" },
  modalUsageBox: { borderRadius: 10, padding: 14 },
  modalUsageTitle: { fontSize: 15, fontFamily: "Inter_700Bold" },
  qtyInputRow: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, marginTop: 8 },
  qtyInput: { flex: 1, fontSize: 15, fontFamily: "Inter_500Medium", paddingVertical: 4 },
  qtyInfo: { flexDirection: "row", alignItems: "flex-start", gap: 6, marginTop: 8, paddingHorizontal: 4 },
  modalFooter: { flexDirection: "row", gap: 12, padding: 16, borderTopWidth: 1, borderTopColor: "rgba(0,0,0,0.08)" },
  modalCancelBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 12, borderRadius: 10, gap: 6 },
  modalUseBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 12, borderRadius: 10, gap: 6 },
  modalBtnText: { fontSize: 14, fontFamily: "Inter_600SemiBold", color: "#fff" },
});

export const mobileFlowStyles = StyleSheet.create({
  switchRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, paddingVertical: 4 },
  switchLabel: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  borderedSection: {
    borderLeftWidth: 3, marginBottom: 10, borderRadius: 10, backgroundColor: "transparent", overflow: "hidden",
    ...Platform.select({ web: { boxShadow: "0 2px 8px rgba(0,0,0,0.06)" }, default: {} }),
  },
  majorHeader: { paddingVertical: 10, paddingHorizontal: 14, fontFamily: "Inter_700Bold", fontSize: 14, color: "#fff", textAlign: "center", letterSpacing: 0.3 },
  accHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 12, paddingHorizontal: 14 },
  accHeaderText: { fontFamily: "Inter_700Bold", fontSize: 14, letterSpacing: 0.3 },
  checkCircle: { width: 22, height: 22, borderRadius: 11, backgroundColor: "#22C55E", alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#fff" },
  subHeaderBar: { paddingVertical: 8, paddingHorizontal: 14, borderLeftWidth: 0 },
  sectionBody: { padding: 14, gap: 10 },
  subLabel: { fontSize: 12, fontFamily: "Inter_600SemiBold", marginTop: 4 },
  scoreBtn: { width: 34, height: 34, borderRadius: 17, borderWidth: 1.5, borderColor: "#D1D5DB", alignItems: "center", justifyContent: "center", backgroundColor: "#F9FAFB" },
  scoreBtnText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: "#374151" },
  radioBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1.5, borderColor: "#D1D5DB", backgroundColor: "#F9FAFB" },
  radioBtnText: { fontSize: 12, fontFamily: "Inter_600SemiBold", color: "#374151" },
  noticeBox: { padding: 10, borderRadius: 6, marginTop: 6 },
});
